export const Types = { 
    NOTE_ADD_NEW: 'NOTE_ADD_NEW', 
    NOTE_EDIT: 'NOTE_EDIT', 
    NOTE_EDIT_CANCEL: 'NOTE_EDIT_CANCEL',
    NOTE_EDIT_SAVE: 'NOTE_EDIT_SAVE',
    NOTE_ARCHIVE_TOGGLE: 'NOTE_ARCHIVE_TOGGLE',
    NOTES_ARCHIVE_TOGGLE: 'NOTES_ARCHIVE_TOGGLE',
    NOTE_REMOVE: 'NOTE_REMOVE',
    NOTES_ALL_VISIBLE_REMOVE: 'NOTES_ALL_VISIBLE_REMOVE',
}

