const mockedNotes = {
    // "notes": [],
    "notes": 
                    [{ "id": "1", 
                        "name": "alala", 
                        "dateCreated": "27/02/2171", 
                        "category": "Task", 
                        "content": "some content", 
                        "dateEdited": "", 
                        "archived": true,
                    },    
                    {   "id": "2", 
                        "name": "The theory of evolution", 
                        "dateCreated": "11/12/2035", 
                        "category": "Idea", 
                        "content": "Implement newest", 
                        "dateEdited": "", 
                        "archived": false,
                    },
                    {   "id": "3", 
                        "name": "ewrewroewr", 
                        "dateCreated": "11/12/2035", 
                        "category": "Random Thought", 
                        "content": "ytpoytrypoweere,mmrerop", 
                        "dateEdited": "11/12/2035", 
                        "archived": true,
                    },  
                    { "id": "4", 
                    "name": "alala", 
                    "dateCreated": "31/10/2145", 
                    "category": "Task", 
                    "content": "some content", 
                    "dateEdited": "", 
                    "archived": false,
                },    
                {   "id": "5", 
                    "name": "The theory of evolution", 
                    "dateCreated": "04/01/1978", 
                    "category": "Idea", 
                    "content": "Implement newest", 
                    "dateEdited": "", 
                    "archived": false,
                },
                {   "id": "6", 
                    "name": "ewrewroewr", 
                    "dateCreated": "01/07/2000", 
                    "category": "Random Thought", 
                    "content": "ytpoytrypoweere,mmrerop", 
                    "dateEdited": "11/12/2035", 
                    "archived": true,
                },    
                {   "id": "7", 
                "name": "ewrewroewr", 
                "dateCreated": "07/09/2011", 
                "category": "Random Thought", 
                "content": "ytpoytrypoweere,mmrerop", 
                "dateEdited": "11/12/2035", 
                "archived": false,
            }],
    "showArchivedNotes": false, 
    "editNoteId": "none",           
                
}

export default mockedNotes